name: Pull Request Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Linting check
        run: npm run lint

      - name: TypeScript check
        run: npm run type-check

      - name: Build with Next.js
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: .next

      - name: Success
        run: echo "🚧 Build successful 🚧"      